### ISSUE TITLE
Add endpoint with group teachers list and teacher groups list

### ISSUE THREAD

**Issue by MrPaschenko** [kpi-ua/schedule.kpi.ua#100]
For example, by calling https://schedule.kpi.ua/api/schedule/teachers?groupId=52fdce67-88b6-4252-8e7b-c73236b3063f client will receive json with all teachers that teach group `ІМ-11`.

Same with teachers, by calling https://schedule.kpi.ua/api/schedule/teachers?lecturerId=6a8864a9-4900-4e22-81eb-8d8522d72b78 client will receive groups that have `Шемсединов Тимур Гафарович` in schedule.

**Comment by Oleks-Y** [comment]
Suddenly, our API not oriented so far for third-party usage, so those changes can be implemented only if we will add that functionality to our frontend. @ernado-x
