### ISSUE TITLE
Wrong week and day is shown

### ISSUE THREAD

**Issue by Llamin** [kpi-ua/schedule.kpi.ua#131]
For ex: today is Thursday of first week, and the site shows, that today is wednessday of second week
This semester started on 5, September with first week on schedule

Media included: 
1. ![photo_2022-09-20_18-27-06](https://user-images.githubusercontent.com/7538239/191299847-24ebcd76-80b7-4a4a-affe-bae5cac31e67.jpg)

2. ![photo_2022-09-20_18-26-22](https://user-images.githubusercontent.com/7538239/191299643-00ab9a76-adf6-4b43-9635-3ccbac0e2437.jpg)

**Comment by s3rbug** [comment]
@Oleks-Y looks like backend issue: https://schedule.kpi.ua/api/time/current always returns currentWeek: 2

**Comment by Oleks-Y** [comment]
Seems to be fixed now
