### ISSUE TITLE
Outdated data in Schedule API

### ISSUE THREAD

**Issue by qqlexa** [kpi-ua/schedule.kpi.ua#200]
Let's investigate bug with special group (ТР-31мн) schedule data. It is not actual

https://schedule.kpi.ua/?groupId=e3fa69c6-0347-4901-b5bb-9f45176abcec
https://api.campus.kpi.ua/schedule/lessons?groupId=e3fa69c6-0347-4901-b5bb-9f45176abcec
![image](https://github.com/kpi-ua/schedule.kpi.ua/assets/37111337/921c65a1-ef7f-48e9-bdbb-52cdaecf942d)

roz.kpi.ua:
It is currently not working.

**Comment by qqlexa** [comment]
Data from roz.kpi.ua:
![image](https://github.com/kpi-ua/schedule.kpi.ua/assets/37111337/1cf1cf68-66d3-4db8-b82d-0e1a69de313a)
![image](https://github.com/kpi-ua/schedule.kpi.ua/assets/37111337/83aa9766-f8a7-45ec-b1e1-c31ba4d08600)

**Comment by ernado-x** [comment]
Added internal Jira story: https://kpiua.atlassian.net/browse/KB-10
