### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by MrPaschenko** [kpi-ua/schedule.kpi.ua#74]
<img width="80" alt="Снимок экрана 2022-04-28 в 02 16 50" src="https://user-images.githubusercontent.com/64316080/165646572-db1fb1e4-7a6e-4dec-a2c9-2ee8fdbae923.png">

I want to update favicons according to these two guides:
- https://habr.com/ru/company/htmlacademy/blog/336698/
- https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

So it would be nice, if you have .svg logo for this project.

Currently, the only thing I found is logo with beta label, but in case you have one without this label, please commit it to repository!

**Comment by MrPaschenko** [comment]
Found it!

https://github.com/kpi-ua/schedule.kpi.ua/blob/1a6bf6fee7620a391a52b6676be3c38f84fbbabd/src/assets/logo.svg

Can I use this logo to do favicons or do you have better version of it?

**Comment by ernado-x** [comment]
@Oleks-Y can you help?

**Comment by Oleks-Y** [comment]
looks like one above is correct

**Comment by MrPaschenko** [comment]
Thanks!
