### ISSUE TITLE
Can I use logo?

### ISSUE THREAD

**Issue by MrPaschenko** [kpi-ua/schedule.kpi.ua#78]
I am working on iOS application based on your API: https://github.com/MrPaschenko/Schedule-KPI
Can I use your logo? It will look like this:
<img src="https://user-images.githubusercontent.com/64316080/167402697-3ee66d38-f254-4854-8ef4-bd74591eda6a.png" alt="3" width="100"/>
And on the iPhone like this:
<img src="https://user-images.githubusercontent.com/64316080/167402872-8953f86a-012d-4439-9629-95817294f52b.png" alt="3" width="200"/>

**Comment by ernado-x** [comment]
Yes, you can
