### ISSUE TITLE
Empty schedule

### ISSUE THREAD

**Issue by MrPaschenko** [kpi-ua/schedule.kpi.ua#79]
Some groups have empty schedule on schedule.kpi.ua, while everything is ok on rozklad.kpi.ua. For example, "ІМ-14 іноземці":
http://rozklad.kpi.ua/Schedules/ViewSchedule.aspx?g=eabdaa5f-26b5-4561-b1ca-35c3973ae2aa
https://schedule.kpi.ua/?groupName=ІМ-14
Probably, the issue is in space in group name

**Comment by ernado-x** [comment]
@Oleks-Y could you please take a look?

**Comment by MrPaschenko** [comment]
Any update?
Maybe you also have repository with API, so I can contribute there?

**Comment by Oleks-Y** [comment]
I think problem might be in group name, because full group name is `ІМ-14 іноземці`, so it was saved incorrectly.

**Comment by MrPaschenko** [comment]
I think it might be better to use group id instead of name for query in API ("eabdaa5f-26b5-4561-b1ca-35c3973ae2aa" instead of "ІМ-14 іноземці"). Is there any way I can help to get this change to be done?

**Comment by Oleks-Y** [comment]
Yes, now I see that querying by group name won't work actually, and even more, the group name is not unique across all faculties, so changes are currently in progress. There is some work on the backend left, mostly testing of updated parser and endpoint to get schedule by group id.

**Comment by MrPaschenko** [comment]
That's great, thank you! Any help needed at the time?

**Comment by MrPaschenko** [comment]
Now, with group id instead of name in API query, there is still problem with groups with foreign students, for example:

- `ІП-07 ін` (83063c9c-d3b0-4cc0-9f78-e9f586f80292): [rozklad.kpi.ua](http://rozklad.kpi.ua/Schedules/ViewSchedule.aspx?g=83063c9c-d3b0-4cc0-9f78-e9f586f80292) and [schedule.kpi.ua](https://schedule.kpi.ua/?groupId=83063c9c-d3b0-4cc0-9f78-e9f586f80292)
- `ІМ-14 іноземці` (eabdaa5f-26b5-4561-b1ca-35c3973ae2aa): [rozklad.kpi.ua](http://rozklad.kpi.ua/Schedules/ViewSchedule.aspx?g=eabdaa5f-26b5-4561-b1ca-35c3973ae2aa) and [schedule.kpi.ua](https://schedule.kpi.ua/?groupId=eabdaa5f-26b5-4561-b1ca-35c3973ae2aa)

Perhaps, there is some error is parser, which does not see groups with space in name

**Comment by MrPaschenko** [comment]
At the moment, there is no way to check schedule for such groups as rozklad.kpi.ua redirects to schedule.kpi.ua 😕

**Comment by ernado-x** [comment]
@MrPaschenko  @Oleks-Y is this problem still actual?

**Comment by MrPaschenko** [comment]
Yes, still cannot find `ІМ-14 іноземці`, for example

**Comment by Oleks-Y** [comment]
Crosschecked, group was missed in initial group list, so problem not with parser. I will ask for update of group list.
