### ISSUE TITLE
Some groups have wrong location with prefix "пол" and suffix "янг". 

### ISSUE THREAD

**Issue by Masedko** [kpi-ua/schedule.kpi.ua#99]
![image](https://user-images.githubusercontent.com/78966998/178587653-bf208f53-2e3d-4e30-a73c-5e08c33e6366.png)
![image](https://user-images.githubusercontent.com/78966998/178587658-09abed6b-0978-4ac6-b50b-f8a76677766e.png)

**Comment by Oleks-Y** [comment]
That's how location stored in university's database, not sure if we can change that data
